INSERT INTO products (name, producer, count, price) VALUES ('product_1', 'producer_1', 3, 50);
INSERT INTO products (name, producer, count, price) VALUES ('product_2', 'producer_2', 6, 150);
INSERT INTO products (name, producer, count, price) VALUES ('product_3', 'producer_3', 7, 250);
INSERT INTO products (name, producer, count, price) VALUES ('product_5', 'producer_1', 9, 350);
INSERT INTO products (name, producer, count, price) VALUES ('product_6', 'producer_2', 11, 450);
INSERT INTO products (name, producer, count, price) VALUES ('product_7', 'producer_1', 2, 70);
INSERT INTO products (name, producer, count, price) VALUES ('product_8', 'producer_4', 4, 120);
INSERT INTO products (name, producer, count, price) VALUES ('product_9', 'producer_2', 6, 50);
INSERT INTO products (name, producer, count, price) VALUES ('product_10', 'producer_3', 8, 10);